Repository stevent-team/react-party, pull requests merged in 2022-08, with the labels that each got.

#4 Check that canvas ref is set when resizing
  lib/useConfetti.jsx
Labels: bug

#5 Implement duration option for showing confetti
  index.html
  lib/useConfetti.jsx
  lib/util/index.js
  package.json
Labels: enhancement

#6 Create control panels on sample project
  package.json
  sample/App.jsx
  yarn.lock
Labels: enhancement

#7 The Kill Zone
  lib/useConfetti.jsx
  sample/App.jsx
Labels: enhancement

#8 Refactor api and update drawing logic
  README.md
  index.html
  lib/config/index.js
  lib/drawing.js
  lib/index.js
  lib/main.js
  lib/useConfetti.jsx
  lib/util/drawing.js
  lib/util/index.js
  package.json
  sample.vite.config.js
  sample/App.jsx
  vite.config.js
Labels: documentation, enhancement
